In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [4]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [6]:
bow=cv.fit_transform(df['text'])

In [8]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [12]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [14]:
cv.transform(['campusx watch and write comment of ']).toarray()

array([[1, 1, 0, 1, 1]])

In [17]:
# for ngram


cv=CountVectorizer(ngram_range=(2,2))
bi_gram=cv.fit_transform(df['text'])

In [18]:
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [19]:
cv=CountVectorizer(ngram_range=(3,3))
tri_gram=cv.fit_transform(df['text'])

In [20]:
print(cv.vocabulary_)

{'people watch campusx': 2, 'campusx watch campusx': 0, 'people write comment': 3, 'campusx write comment': 1}


In [21]:
print(tri_gram[0].toarray())

[[0 0 1 0]]
